[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SITE_URL = "https://gusmack1.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/reviews/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/restaurant/:id"
  to = "/restaurants/:id"
  status = 301

[[redirects]]
  from = "/review/:slug"
  to = "/reviews/:slug"
  status = 301


