name: Scrape and Publish Reviews

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci
        working-directory: gusmack-food-reviews

      - name: Run scraper
        run: npm run scrape || true
        working-directory: gusmack-food-reviews

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "chore: automated scrape" || echo "No changes"
      - name: Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

